language: node_js
node_js:
- lts/*
script:
- yarn run build:demo
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: demo-build
  github-token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
