language: node_js
node_js:
- lts/*
script:
- yarn run build:demo
deploy:
  provider: pages
  cleanup: true
  local_dir: demo-build
  github_token:
    secure: p01X6XTrf2shMzLvxi0UXiCoGeotqA/uPABl3WXcpV5Qyy33ffJnxDQ95t1I5E85SgiVLUpQOSF3ThCiy/Dz2Bu6AXSdhsB+mvAID1b7cgliDrsMc6fLSRjVmX22gyxgo5uaYgjKCKpi28U2Hrj2E7RFxUHag6nOlk6KLXkWPpdCBIOTSE21yWYmThYqXjbbLmXwBDWT4/ZyYj1EtUb0Qcd6fJJW8dKt4UvJquGQWfJeoRXuvVM1YLVV7Oa76stdJAv2speBvftRJMhQbGmFGZug5kZcWGwapijpG206GpcrbctCCIKvrrRazKt4dxC5+ase67DXPYaKvKUAZxIfP2oD2r/CvYw1MvMc3F9VADU7qIzRgxlStoyi7ofqoi0A16vTmhnbbjkyGaazyNm/DmOplISXzRoH9gJq534kERB8z4pPMSLLtPiB6mOzBiIEfxS4uuQTkxBRWJ6c5889xFyPBFwQZeCAdaKwmltZ4WAlogGmB8am40RFINiTvRHSILa8VsTOcbCVpEW6qbRVNH2UHpXa7r3HGY1L0iCgDck2MIFqOUuOp/tCr0YUVGb9CiwYr/c/gTXogXHM4kHou+GWXE3I41ygqaN7IddLIGgSyOV6JG4EIIDS+7WUSzXwvmLZjByMudle7OK7ZgLHr7drQ6KJaBea/zxCRmUWQTk=
  keep_history: true
  on:
    branch: master
