language: node_js
node_js:
- lts/*
script:
- yarn run build:demo
deploy:
  provider: pages
  cleanup: true
  local_dir: demo-build
  token:
    secure: kNmgPWIxZmOB5N8TEddVkJtm8tHL1+FTf82FXtrmU6fQQZfNW9G9GEyZOUsRzQk2qH3WL1T36ffPyLr6MdrUf+S3IMm+bmwhhj/whaBdZdEcGoV2uxgNWKASRdZyeRBptYLbCUTElYYPUz3R5y4pYlyygtPJQtjfKESa3awEba0JqaXHo1R4FSSSKUCmHsO3wKHxHc4WJF1aea7RiQNZ62XWPoCiiDZ+XVQVC9468Z2dNq5F3rGqE5gBw544EufOFmMaOeUjtzO7jROn5Mt18XtIpaIazMhahp/8xMjwskuM4z7UqztHFUEs0HZMvbVYBIeuG6Pl5egtyUkC7ubjmeS0tDc9SW+EBt+/OrgO1LP+wMUA3JJ4FoDDj9fpWkPcvN+3+NQ7SbjU2KeinJaIB5PqgsL7Mr8Abx/nwlD9GgVr/fvK/yCAtIMCttBYAjO1DwOVqoav0YvVB6kBKuJx8I0o2u0MwydZr4A8J07mCAq/mHDoI//Ftus6xi8Qe8Oc5V8I37YpJ/ACwoEolNlpxcZpAGqzP2artmWSCavxlLVD2/777r/W0x2rTZTG/jtvTYLT2eUP+mnbU1abKCaknaZDY+5ry5YDZ+xGoQl5sKUTEBZ7Br8yuo9WHUNzaKoVEXI1rGVRDsxKG3iYCaw0bxk4cHLITjjhYh+1Qu/S0lA=
  keep_history: true
  on:
    branch: master
